#ifndef INCLUDED_TEST_RESOURCES_H
#define INCLUDED_TEST_RESOURCES_H

#ifndef WISEKMA_KNOWLEDGE
# define WISEKMA_KNOWLEDGE "@wisekma_KNOWLEDGE@"
#endif

#ifndef IZENECMA_KNOWLEDGE
# define IZENECMA_KNOWLEDGE "@izenecma_KNOWLEDGE@"
#endif

#endif // INCLUDED_TEST_RESOURCES_H
