/**
 * @file core/common/parsers/ConditionOperatorTable.cpp
 * @date Created <2010-07-12 14:28:26>
 *
 * This file is generated by generators/condition_operator_table.rb from
 * config file generators/condition_operator_table.yml. Do not edit this
 * file directly. Please read the config file, update options there and
 * re-run the ruby script to update this file.
 */
#include "ConditionOperatorTable.h"

namespace sf1r {

ConditionOperatorTable::table_type ConditionOperatorTable::table_;
boost::once_flag ConditionOperatorTable::flag_;

void ConditionOperatorTable::init()
{
    OperatorInfo info;

    info.name = "=";
    info.minArgCount = 1;
    info.maxArgCount = 1;
    table_["="] = info;
    table_["equal"] = info;
    table_["=="] = info;

    info.name = "<>";
    info.minArgCount = 1;
    info.maxArgCount = 1;
    table_["<>"] = info;
    table_["not_equal"] = info;
    table_["!="] = info;

    info.name = "<";
    info.minArgCount = 1;
    info.maxArgCount = 1;
    table_["<"] = info;
    table_["less_than"] = info;

    info.name = "<=";
    info.minArgCount = 1;
    info.maxArgCount = 1;
    table_["<="] = info;
    table_["less_than_or_equal"] = info;

    info.name = ">";
    info.minArgCount = 1;
    info.maxArgCount = 1;
    table_[">"] = info;
    table_["greater_than"] = info;

    info.name = ">=";
    info.minArgCount = 1;
    info.maxArgCount = 1;
    table_[">="] = info;
    table_["greater_than_or_equal"] = info;

    info.name = "between";
    info.minArgCount = 2;
    info.maxArgCount = 2;
    table_["between"] = info;
    table_["range"] = info;

    info.name = "in";
    info.minArgCount = 1;
    info.maxArgCount = 4294967295;
    table_["in"] = info;

    info.name = "not_in";
    info.minArgCount = 1;
    info.maxArgCount = 4294967295;
    table_["not_in"] = info;

    info.name = "starts_with";
    info.minArgCount = 1;
    info.maxArgCount = 1;
    table_["starts_with"] = info;

    info.name = "ends_with";
    info.minArgCount = 1;
    info.maxArgCount = 1;
    table_["ends_with"] = info;

    info.name = "contains";
    info.minArgCount = 1;
    info.maxArgCount = 1;
    table_["contains"] = info;

}

}

